services:

  db:
    image: postgres:16
    container_name: Photoview-DB
    hostname: photoview-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "photoview", "-U", "photoviewuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume1/docker/photoview/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: photoview
      POSTGRES_USER: photoviewuser
      POSTGRES_PASSWORD: photoviewpass
    restart: unless-stopped

  photoview:
    image: viktorstrate/photoview:2.4.0
    container_name: Photoview
    hostname: photoview
    security_opt:
      - no-new-privileges:false
    read_only: false
    user: 1000:1000
    healthcheck:
      test: curl -f http://localhost:4000/ || exit 1
    ports:
      - 7354:4000
    volumes:
      - /volume1/docker/photoview/cache:/app/cache:rw
      - /volume1/docker/photoview/photos:/photos:ro
    environment:
      PHOTOVIEW_DATABASE_DRIVER: postgres
      PHOTOVIEW_POSTGRES_URL: postgresql://photoviewuser:photoviewpass@photoview-db:5432/photoview
      PHOTOVIEW_LISTEN_PORT: 4000
      PHOTOVIEW_MEDIA_CACHE: /app/cache
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
